# Site
repository: faoliveira/faoliveira.github.io
encoding: UTF-8
darkmode: false

# Content configuration version
version: 2

# favicon: images/favicon.ico

# Personal info
name: Felipe Oliveira
title: Business Analyst | Analytics
email: felipe@felipeo.me
website: felipeo.me
url: "https://felipeo.me"

# Google Analytics
google_analytics: UA-76828181-2

# Social links
# twitter_username: facespics
github_username:  faoliveira
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: faoliveiras
linkedin_username: faoliveiras
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  After realizing that I would not become a professional athlete and wasn't close, I sought through engineering to absorb analytical knowledge and problem solving to seek to understand setbacks in several areas. In this way generating knowledge for competitive advantage.

  I’m always in a state of learning, because I believe in active growth. Innovating today is imperative.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: San Francisco Bay Area Bike Share Data Analysis
        # link_text: Project Website
        additional_links:
          - title:  faoliveira.me/projects/nd110
            icon: fab fa-github
            url: https://github.com/faoliveira/nd110
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Analysis of public dataset about bicycle trips under Bay Area Bike Share program for the Udacity Nanodegree using Jupyter Notebook

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Diageo
        link: diageo.com
        # link_text: boringcompany.com
        sub_title: Senior Data Analyst
        caption: Jan 2020 - Present
        description: |

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Solar Coca-Cola
        link: solarbr.com.br
        sub_title: Marketing Analyst
        caption: Mar 2018 - Sep 2019
        description: | # this will include new lines to allow paragraphs
           - Performance evaluation of the products in each region; 
           - Evaluate price movement opportunities in each market; 
           - Market analysis and positioning of hydration category products; 
           - Follow-up of projects and the implementation of communication plans. 

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Coca-Cola
        link: cocacolabrasil.com.br
        sub_title: Planning Still Beverages Intern
        caption: Aug 2016 - Mar 2018
        description: | # this will include new lines to allow paragraphs
           - Analysis of performance indicators and market trends, supporting the planning process of the area; 
           - Analyzes and studies of performance indicators of the Still Beverages categories; 
           - Interaction between the areas of the company and bottlers to support the implementation of planned market activities in the company's Business Plan, such as approval of communication materials, follow-up of internal activities; 
           - Perform the tracking of the main market activities and product launches; 
           - Control of the management routines of market investment indicators

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Adtalem Educacional do Brasil
        link: adtalembrasil.com.br
        sub_title: Process Intern
        caption: Jan 2014 - Jul 2015
        description: | # this will include new lines to allow paragraphs
            Creation and monitoring of indicators for presentation to the area manager. Summed with process mapping to standardize the attendance of the educational institutions that Devry Brazil controls.

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Casa Magalhães
        link: casamagalhaes.com.br
        sub_title: IT Intern
        caption: Fev 2012 - Oct 2012
        description: | # this will include new lines to allow paragraphs
            Support for the company tax program for direct customers and resellers.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Universidade de Fortaleza
        caption: 2012 - 2018
        sub_title: B.Eng Industrial engineering

  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Instituto Federal de Educação, Ciência e Tecnologia do Ceará
        caption: 2009 - 2012
        sub_title: Telecommunications

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
     Alongside my interests in data science and industrial engineering some of my other interests are:
      - Try to understand why some people think Earth is flat?
      - Gaming
      - Watch some dubious movies
     - After  attempts, try to go back to the gym like a logarithmic growth



# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
