# Site
repository: faoliveira/faoliveira.github.io
encoding: UTF-8
# favicon: images/favicon.ico

# Personal info
name: Felipe Oliveira
title: Business Analyst | Analytics
email: hi@felipeo.me
website: felipeo.me

# Social links
# twitter_username: facespics
github_username:  faoliveira
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: faoliveiras
linkedin_username: faoliveiras
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  After realizing that I would not become a professional athlete and wasn't close, I sought through engineering to absorb analytical knowledge and problem solving to seek to understand setbacks in several areas. In this way generating knowledge for competitive advantage.

  I’m always in a state of learning, because I believe in active growth. Innovating today is imperative.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data science and industrial engineering some of my other interests are:
   - Try to understand why some people think Earth is flat?
   - Gaming
   - Watch some dubious movies
   - After  attempts, try to go back to the gym like a logarithmic growth

# Footer
footer_show_references: false

# Analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-76828181-2         # Required - replace with your tracking id
    anonymizeIp: true      # Optional - Default: false - set to true for anonymized tracking 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-analytics
